### PR TITLE
Adds pagination to QA

### PR DESCRIPTION
**Pull request by freetonik**
Pagination of topics. 

- number of topics per page is controlled by `TOPICS_PER_PAGE` constant in `app/brochure/routes/questions/index.js`
- paginator is visible only if there are more than 1 pages
- paginator adheres to format described in [todo](https://github.com/davidmerfield/Blot/blob/master/todo.txt#L36):
    ```
    [1] 2 3 4 5 ... 945 Next                163,073 questions 
    ```
- urls for pages are in format `/questions/page/N`. @davidmerfield do you think this is okay? Alternatives are
    - `/questions/pageN`
    - `/questions?page=N` (I believe this isn't ideal, because url params are better suited for filtering)

### CODE REVIEW

**Comment by freetonik** [comment]
Also, I don't think I understand how to properly serve 404 (in case of accessing non-existent page in QA pagination).

**Comment by davidmerfield** [comment]
@freetonik Excellent, I like the URL format /page/1 /page/2 etc.

I refactored the middleware function – please let me know if you have any thoughts or if I overlooked something.

What are your thoughts on the change to the question ordering? Per ab86cf9 questions are sorted by newness, regardless of date of replies. Happy to reconsider as always.

As for 404s:

- Express middleware gets invoked with a third `next` function parameter. If you call that, you send the request further down the stack of middleware, eventually hitting the brochure's [404 and error handling functions](https://github.com/davidmerfield/Blot/blob/master/app/brochure/index.js#L103-L129). 
- If you invoke `next` with an error as first parameter, Express will skip all middleware that only accepts three arguments (`req`, `res`, `next`) until it finds middleware that accepts four arguments (`err`, `req`, `res`, `next`).
- If we want custom 404/error pages only for the QA section, we can declare that middleware at the end of the Question router, but still follow the `next()` pattern to direct the request there.

**Comment by davidmerfield** [comment]
@freetonik Just plucked a few of my commits off this PR that were a bit out of scope

This looks good to me – please let me know once you review.

Happy to discuss the question of topic ordering (by reply? by creation date?)

**Comment by freetonik** [comment]
Thanks for the clarification regarding 404 and middlewares!

>Happy to discuss the question of topic ordering (by reply? by creation date?)
Originally, I decided to sort by reply date, but that was me thinking about the QA as a discussion forum, rather than a support system. Until the nature of the QA section changes, I believe questions should be sorted by creation date, as per your modification. 

I also think that unanswered questions should be marked somehow. Maybe, the `0 replies` badge should be of some warning-yellow color.

**Comment by davidmerfield** [comment]
Great, I will deploy this soon. 

Makes sense regarding ordering. I'm not opposed to it growing into more of a forum as Blot grows – perhaps then we change the default ordering. One day I would like eventually to have 'mass' topics with many answers like 'What text editor do you use?', 'What have you built?' etc. that we might want to boost to top of the index when activity occurs.

For now it might be worth boosting/stickying unanswered questions to the very top? I will experiment with colour options

**Comment by freetonik** [comment]
Yeah, I like the idea of stickying unanswered questions to the very top!

**Pull request merged**
