### PR TITLE
QA forum

### PR DESCRIPTION
**Pull request by freetonik**
Hey @davidmerfield
This is a very rough prototype not ready for merging. Demo:

https://user-images.githubusercontent.com/2665931/105720519-2f32f300-5f2c-11eb-9083-7b953463f587.mov

TODO until ready to merge:
- styling
- production-ready DB configuration/secrets/migration
- CSRF
- markdown render

### CODE REVIEW

**Comment by davidmerfield** [comment]
Excellent, this looks great. 

I can take care of CSRF in a separate PR using https://www.npmjs.com/package/csurf. I have it set up on the dashboard, have been meaning to add it to the brochure for a while

**Comment by davidmerfield** [comment]
Added CSRF to sign-up and log-in in #398 @freetonik are you ok to include this into the routes?

**Comment by freetonik** [comment]
Cool! Will do, @davidmerfield

**Comment by freetonik** [comment]
Hey @davidmerfield 

This is now ready to review and merge. Notes:

- Tests fail due to `127.0.0.1:5432` being inaccessible in the testing env. Could you please help me set Postgres up in there? After that, I could write unit tests that would verify posting, rendering and access control.
- I managed with a single DB table that references itself in order to produce one-to-many relations (parent item to child items). I have also added constraints on the table columns that prevent invalid combinations of values (e.g. parent item must have a title; child item must have parent, but must NOT have title). I hope the structure and SQL queries don't look too convoluted. I am open to re-factoring this into multiple tables.
- There are no migrations atm. DB creation and table creation is done via two scripts: `scripts/db/create-postgres-db.js` and `scripts/db/create-postgres-table.js`. As soon as we start making improvements to the QA section, I think we'd need to introduce at least rudimentary migrations. It'd be nice to keep them simple, e.g. raw SQL, ordered scripts, no new dependencies.
- Postgres connection is done through 4 env variables (see [this change](https://github.com/davidmerfield/Blot/pull/397/commits/7e8a8af1b808f77f28d7f4a99b72ea89ebd55a54#diff-68af175f365b070b4bc38a197acbcb336c50e7eca6b18f8e8f70058165429b23))
- I am using Postgres 12.3 in dev.

**Comment by davidmerfield** [comment]
Excellent, after a cursory check it looks good. I haven't deployed postgres in a production environment before, so I will do a bit of research and get this public as soon as possible

**Review by davidmerfield — APPROVED** [review]

**Comment by davidmerfield** [comment]
Deployed!

https://blot.im/questions

Thanks @freetonik, this is great, will add a few starter questions

**Pull request merged**
