### PR TITLE
Adds iCloud client

### PR DESCRIPTION
**Pull request by davidmerfield**
- [ ] **Determine how best to share a given folder in iCloud drive with a given email address programatically** I have a draft applescript in `app/clients/icloud/server/applescript.scpt`
  - [ ] we could also use browser automation? could this even be done completely on Blot's server, with no rented mac?
- [ ] Finish the UI stuff to make the client work on Blot's dashboard
- [ ] Create iCloud account for Blot 
- [ ] Write script to init git client for iCloud clients
---
- [x] Determine the manner of communication from Blot's server to the Mac
- [x] It seems like montaigne.io are doing something similar [with Apple notes](https://docs.montaigne.io/guides/new-site). Is it worth contacting them for tips? We have corresponded in the past
- [x] There is an unofficial API: https://github.com/MauriceConrad/iCloud-API
- [x] Determine the best company to rent a Mac server, options include:
    - https://www.rentyourmac.com/cloud/product/mac-mini-late-2014/
    - https://www.scaleway.com/en/pricing/?tags=available,baremetal-macminim1-macminim1
    - https://www.greenmini.nl/
    - https://www.macstadium.com/
    - https://www.oakhost.net/
    - https://www.hetzner.com/
    - https://www.hostmyapple.com/
---
 - [ ] Release a beta
   - [ ] [Nat](https://mail.google.com/mail/u/0/#inbox/FMfcgzGqQSTbjBLgXjSTDVCTblLhvbKr) and [Roberto](https://github.com/rmateu) have volunteered for testing
---
- [ ] Tell people who are interested in using the iCloud client
  - [ ] [David](https://mail.google.com/mail/u/0/#inbox/FMfcgzGtwWCBwRJKJFcZXtkhBkcCcJGV)
  - [ ] [Andrew](https://mail.google.com/mail/u/0/#inbox/FMfcgxwChJfNnhCDNsffJSjnQHnxdSfh)
  - [ ] [Cristina](https://mail.google.com/mail/u/0/#inbox/FMfcgzGmtFHHXQKNQKppXpHGpkvLjQSD)
  - [ ] [John](https://mail.google.com/mail/u/0/#inbox/FMfcgzGlkPcphtxgswTQccZLfQGwfWhN)
  - [ ] [David](https://mail.google.com/mail/u/0/#inbox/FMfcgxwChJfNfSZgQqjNWLWVHZjwXQrS)
  - [ ] [John](https://mail.google.com/mail/u/0/#inbox/FMfcgxwChJfNTrdmqJwwzCPLrhcQRNWW)
  - [ ] [Dave](https://mail.google.com/mail/u/0/#inbox/FMfcgxwChJfNfLmTVjNGcXZVRWdlrLzp)
  - [ ] [Shawn](https://mail.google.com/mail/u/0/#inbox/FMfcgxwChJfNfRRjzkzpvQjPTCQtqpDx)
  - [ ] [Andrew](https://mail.google.com/mail/u/0/#inbox/FMfcgxwChJgWDpnsGBCXsCwkxRZnXMph)
  - [ ] [Chris](https://mail.google.com/mail/u/0/#inbox/FMfcgxwC1hJjqgsvKxxVgFdbXvxNTHTsz)
  - [ ] [Leo](https://mail.google.com/mail/u/0/#inbox/FMfcgzGqQSRJwdnCqhZNBPtRxpWlbWXv)
  - [ ] [Kerim](https://mail.google.com/mail/u/0/#inbox/FMfcgxwChSJkptkQxlqTjsDCtdTgMWXv)
  - [ ] [Nat](https://mail.google.com/mail/u/0/#inbox/FMfcgzGqQSTbjBLgXjSTDVCTblLhvbKr)
  - [ ] [Wilt](https://mail.google.com/mail/u/0/#inbox/FMfcgxwChcgKzMGXdrHMVhrjsjJnnBzk)
  - [ ] [John](https://mail.google.com/mail/u/0/#inbox/FMfcgxwDqfMPDQnSTBSsWXdtfkVdJzdD)
  - [ ] [Arlo](https://mail.google.com/mail/u/0/#inbox/FMfcgxwJWrZRLJddkZSdrMVxrNkTZLKn)
  - [ ] [Anders](https://mail.google.com/mail/u/0/#inbox/FMfcgxwKkRFxsDShhsHGNcdRqwHFMmJM)
  - [ ] [Victor](https://mail.google.com/mail/u/0/#inbox/FMfcgzGkbDVrLFlwcgwDddsVPJBVKSvW)
  - [ ] [Ken](https://mail.google.com/mail/u/0/#inbox/FMfcgzGpGdmpXpTBPzTgnrSHLMjcMGKq)
  - [ ] [Sebastien](https://mail.google.com/mail/u/0/#inbox/FMfcgzGpGwtWnjjFvGfHLnHfRzgrcjGW)
  - [ ] [Austin](https://mail.google.com/mail/u/0/#inbox/FMfcgzGsltKdZxhmCMXvhJjpWxkVDpTq)
  - [ ] [Kirk](https://mail.google.com/mail/u/0/#inbox/FMfcgzGsmDsZvbQwRgRLgJVDXHDJshxK)
  - [ ] [Ray](https://mail.google.com/mail/u/0/#inbox/FMfcgzGsmNMjKsNbfdTbXCPWGkzpxkTk)
  - [ ] [Jan](https://mail.google.com/mail/u/0/#inbox/FMfcgzGsmXBHFvkklRwGzBwfVwfvxSGb)
  - [ ] [Pete](https://mail.google.com/mail/u/0/#inbox/FMfcgzGtwzjcGlzctBZfjZCnJpbZrqrQ)
  - [ ] [Noa](https://mail.google.com/mail/u/0/#inbox/FMfcgzGtxSsdCkFmHPJSZCnvgSpBFqKm)
  - [ ] [Michael](https://mail.google.com/mail/u/0/#inbox/FMfcgzGwHLjnsCXDFckPMjJMrfDrptdD)
  - [ ] [Eric](https://mail.google.com/mail/u/0/#inbox/FMfcgzGwHLjmmqsDpLvWDTRJMDzLMVrN)
  - [ ] [Lex](https://mail.google.com/mail/u/0/#inbox/FMfcgzGwHLjmmpknrnmxgWWBktzlgcxF)
  - [ ] [Aron](https://mail.google.com/mail/u/0/#inbox/FMfcgzGwHVKqlCcMrbtjnZDKNqBdhVbd)

### CODE REVIEW

**Comment by rmateu** [comment]
+1 for testing!

**Comment by davidmerfield** [comment]
@rmateu Great, I've added you to the list

**Comment by aewhite77** [comment]
Also love to assist in testing

**Comment by davidmerfield** [comment]
@aewhite77 Excellent, please [send us an email](https://blot.im/contact) and I'll add you to the list to be notified

**Comment by aewhite77** [comment]
I would love to test the icloud sync and will move my blog from Dropbox over to test for you.

**Comment by podviaznikov** [comment]
> It seems like montaigne.io are doing something similar [with Apple notes](https://docs.montaigne.io/guides/new-site). Is it worth contacting them for tips? We have corresponded in the past

@davidmerfield happy to help. iCloud for Blot should be very doable. I think the only small problem is the flow to Share folders in iCloud. It's not as straightforward as Dropbox that creates App folder for the user. But it's also doable.

**Comment by shewcc** [comment]
I would love to test iCloud sync. I've been an iCloud (2TB) user for years and it doesn't make sense to spend another $15 on DropBox or Google Drive. Plus I have come across some Google Drive sync issues, like failing to delete an automatically generated image post. Would love to see iCloud in the lineup!

**Comment by ltgreer** [comment]
Looking forward to iCloud sync!

**Comment by logorrhoea** [comment]
If this still needs testing, happy to be a tester. Holding off installing Dropbox on my Mac if iCloud sync is near to being released.

**Comment by juter** [comment]
Hey, long time Blot user and have been waiting for this for a while - would be happy to test if you're still in need of testers.

**Comment by davidmerfield** [comment]
I've decided that I will wait for Apple is release an iCloud Drive API until I add support for iCloud to Blot. After my own experimentation with the system, the 'hack' I was planning to use is too unreliable in practice. Since I planned to add sharing in an unofficial manner, the risk of Apple shutting down Blot's iCloud account for a terms of use violation is also higher than I am comfortable with investing the resources required to write and maintain the client.

**Comment by davidmerfield** [comment]
@rmateu @aewhite77 @jasonshew @ltgreer @juter 

I changed my mind: https://github.com/davidmerfield/Blot/pull/868

Will have iCloud ready for beta testing this Tuesday, aiming to have public release this Friday. Please let me know either here or via email: https://blot.im/contact if you want to join the beta

The tips @podviaznikov gave were extremely helpful, thank you

**Comment by davidmerfield** [comment]
It's merged and available to everyone on Blot:

https://blot.im/how/sync/icloud

**Pull request closed without merging**
