### PR TITLE
Adds reminder to use guid property of entry in future RSS feeds

### PR DESCRIPTION
**Pull request by davidmerfield**
Replaces `entry.absoluteURL` with `entry.guid` in `<guid>` field of `feed.rss`. I believe this follows the RSS spec better:

https://www.rssboard.org/rss-specification#ltguidgtSubelementOfLtitemgt

Motivation of this PR is to fix unexpected duplicate post. This occurred when someone:

1. Created a post, it was published to their RSS feed and distributed to subscribed RSS readers
2. Edited title of the post, changing its title-derived permalink in the process, thus changing the value in the `<guid>` tag of the item in their feed
3. The RSS readers correctly identified a 'new' post, since the `<guid>` field had changed, although the post in reality had only its title change.

This PR will use the `guid` property of each entry instead, which will remain constant if the title or content of the post changes, or if the source file for the post is renamed.

@freetonik does this seem reasonable to you?

### CODE REVIEW

**Comment by davidmerfield** [comment]
The downside is this will trigger a flurry of new post notifications in RSS readers for those using an unforked template. Perhaps those templates should be forked?

**Comment by freetonik** [comment]
>@freetonik does this seem reasonable to you?

This feels absolutely reasonable. Especially considering the behavior of certain Markdown editors such as iA Writer that's implicitly recommended to Blot users. Those editors create and auto-save the file, which often results in the exact same scenario: the post was published with some title that the user changes later.

>The downside is this will trigger a flurry of new post notifications in RSS readers for those using an unforked template. Perhaps those templates should be forked?

To be honest, both options seem problematic. Do you think it'd be worth to set `guid` for all existing entries to their `absoluteURL` values, and then ship the unforked templates?

**Comment by davidmerfield** [comment]
Tricky one – the `guid` property is used to identify posts to disqus. Changing this would break comments on those blogs.

One option would be to add a hacky ```if``` statement to the renderer which would which would change the `guid` when rendering an RSS feed for posts published before this change is merged on sites using an unforked template.

One option would be: only change this for newly added templates. I eventually plan to replace all the default templates with high quality rewrites under different names (I'm not happy with the templates right now). Perhaps this change could be introduced gradually into those...

**Comment by freetonik** [comment]
If you don’t feel the need to ship the guid-related change ASAP, and templates updates are realistically on the horizon, I’d say introducing the change gradually with the new templates sounds good.

**Comment by davidmerfield** [comment]
I made a note – will fix this gradually as templates are deprecated

**Comment by davidmerfield** [comment]
Courtesy of @Pinjasaur's [close reading of the spec](https://www.rssboard.org/rss-profile#element-channel-item-guid), we'll want to do this:

```
<guid isPermalink="false">{{guid}}</guid>
```

**Comment by Pinjasaur** [comment]
> Courtesy of @Pinjasaur's [close reading of the spec](https://www.rssboard.org/rss-profile#element-channel-item-guid), we'll want to do this:
> 
> ```
> <guid isPermalink="false">{{guid}}</guid>
> ```

FWIW I opted to directly follow their casing e.g., `isPermaLink` but I'm not 100% sure if that matters. My [feed] currently [validates]. 🤷🏻 

[feed]: https://paul.af/feed.rss
[validates]: https://validator.w3.org/feed/check.cgi?url=https%3A//paul.af/feed.rss

**Comment by davidmerfield** [comment]
@Pinjasaur Noted, thanks!

**Pull request merged**
