### PR TITLE
Adds NODE_PATH for better local requires

### PR DESCRIPTION
**Pull request by freetonik**
This is a proposal to address [this todo](https://github.com/davidmerfield/Blot/blob/master/todo.txt#L814) ("Migrate code from `require('../../../')` to shortcuts in node_modules").

The simplest solution that requires no new dependencies or hacks is to simply set `NODE_PATH` env variable to project root directory. Once set, we can do:

```js
var titleFromSlug = require("app/helper/titleFromSlug");
```

The app already relies on env variables to run, and we already have `BLOT_DIRECTORY` variable. The `NODE_PATH` must be absolute for this to work, therefore this is the only new thing that is needed:

```sh
export NODE_PATH=$(cd $BLOT_DIRECTORY; pwd)
```

There are other possible solutions described [here](https://gist.github.com/branneman/8048520).

What do you think @davidmerfield ? If that approach is fine by you, I will convert all relative requires and push to this branch.

### CODE REVIEW

**Comment by davidmerfield** [comment]
Perfect! I overlooked this completely. 

Let's include the 'app' directory in the path, like this:

```
NODE_PATH=/var/www/blot/app
```

So that we can do this:

```js
var titleFromSlug = require("helper/titleFromSlug");
var Blog = require("models/blog");
```

**Comment by freetonik** [comment]
Cool! I'll push the remaining changes soon.

**Comment by davidmerfield** [comment]
Excellent, just deployed!

**Comment by freetonik** [comment]
I think I'm mostly excited about the fact that nothing broke :D

**Comment by davidmerfield** [comment]
@freetonik Always a joy when that happens

**Pull request merged**
